//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18408
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clalis.Api41 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://liplis.mine.nu/XMLSchema/41", ConfigurationName="Api41.ClalisSoap")]
    public interface ClalisSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/41/ClalisMecab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api41.resMecabResult ClalisMecab(string sentence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/41/ClalisEmotional", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ClalisEmotional(string sentence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/41/ClalisToneEmotional", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ClalisToneEmotional(string sentence, string tone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/41/ClalisTone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ClalisTone(string sentence, string tone);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema/41")]
    public partial class resMecabResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private msgMecabResult[] resWordListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public msgMecabResult[] resWordList {
            get {
                return this.resWordListField;
            }
            set {
                this.resWordListField = value;
                this.RaisePropertyChanged("resWordList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema/41")]
    public partial class msgMecabResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idxField;
        
        private string nameField;
        
        private string posField;
        
        private string pos1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int idx {
            get {
                return this.idxField;
            }
            set {
                this.idxField = value;
                this.RaisePropertyChanged("idx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string pos {
            get {
                return this.posField;
            }
            set {
                this.posField = value;
                this.RaisePropertyChanged("pos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string pos1 {
            get {
                return this.pos1Field;
            }
            set {
                this.pos1Field = value;
                this.RaisePropertyChanged("pos1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClalisSoapChannel : Clalis.Api41.ClalisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClalisSoapClient : System.ServiceModel.ClientBase<Clalis.Api41.ClalisSoap>, Clalis.Api41.ClalisSoap {
        
        public ClalisSoapClient() {
        }
        
        public ClalisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClalisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClalisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClalisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Clalis.Api41.resMecabResult ClalisMecab(string sentence) {
            return base.Channel.ClalisMecab(sentence);
        }
        
        public string ClalisEmotional(string sentence) {
            return base.Channel.ClalisEmotional(sentence);
        }
        
        public string ClalisToneEmotional(string sentence, string tone) {
            return base.Channel.ClalisToneEmotional(sentence, tone);
        }
        
        public string ClalisTone(string sentence, string tone) {
            return base.Channel.ClalisTone(sentence, tone);
        }
    }
}
