//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18034
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clalis.Api {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://liplis.mine.nu/XMLSchema", ConfigurationName="Api.ClalisSoap")]
    public interface ClalisSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/clalisMecabFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api.resMecabResultFull clalisMecabFull(string sentence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/clalisMecab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api.resMecabResult clalisMecab(string sentence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/clalisWakachiGaki", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api.resWakachiGakiResult clalisWakachiGaki(string sentence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/clalisMeishiList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api.resMeishiList clalisMeishiList(string sentence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/clalisTone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api.resTone clalisTone(string sentence, string toneFileUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/clalisEmotional", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api.resEmotional clalisEmotional(string sentence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/clalisToneEmotional", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api.resEmotional clalisToneEmotional(string sentence, string toneFileUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/clalisWebExtractJp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api.resWebSummary clalisWebExtractJp(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/clalisWebExtractJpSentenceList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api.resWebSummaryList clalisWebExtractJpSentenceList(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/clalisWebExtractJpSentenceRelevanceList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api.resWebSummaryList clalisWebExtractJpSentenceRelevanceList(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liplis.mine.nu/XMLSchema/clalisGetNewWordList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clalis.Api.resNewWordList clalisGetNewWordList(int number);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class resMecabResultFull : object, System.ComponentModel.INotifyPropertyChanged {
        
        private msgMecabResultFull[] resWordListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public msgMecabResultFull[] resWordList {
            get {
                return this.resWordListField;
            }
            set {
                this.resWordListField = value;
                this.RaisePropertyChanged("resWordList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class msgMecabResultFull : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idxField;
        
        private string nameField;
        
        private string posField;
        
        private string pos1Field;
        
        private string pos2Field;
        
        private string pos3Field;
        
        private string infetted1Field;
        
        private string infetted2Field;
        
        private string prototypeField;
        
        private string readField;
        
        private string pronunciationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int idx {
            get {
                return this.idxField;
            }
            set {
                this.idxField = value;
                this.RaisePropertyChanged("idx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string pos {
            get {
                return this.posField;
            }
            set {
                this.posField = value;
                this.RaisePropertyChanged("pos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string pos1 {
            get {
                return this.pos1Field;
            }
            set {
                this.pos1Field = value;
                this.RaisePropertyChanged("pos1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string pos2 {
            get {
                return this.pos2Field;
            }
            set {
                this.pos2Field = value;
                this.RaisePropertyChanged("pos2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string pos3 {
            get {
                return this.pos3Field;
            }
            set {
                this.pos3Field = value;
                this.RaisePropertyChanged("pos3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string infetted1 {
            get {
                return this.infetted1Field;
            }
            set {
                this.infetted1Field = value;
                this.RaisePropertyChanged("infetted1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string infetted2 {
            get {
                return this.infetted2Field;
            }
            set {
                this.infetted2Field = value;
                this.RaisePropertyChanged("infetted2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string prototype {
            get {
                return this.prototypeField;
            }
            set {
                this.prototypeField = value;
                this.RaisePropertyChanged("prototype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string read {
            get {
                return this.readField;
            }
            set {
                this.readField = value;
                this.RaisePropertyChanged("read");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string pronunciation {
            get {
                return this.pronunciationField;
            }
            set {
                this.pronunciationField = value;
                this.RaisePropertyChanged("pronunciation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class msgNewWord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private System.DateTime createDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("createDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class resNewWordList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private msgNewWord[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public msgNewWord[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class resWebSummaryList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] resWordListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] resWordList {
            get {
                return this.resWordListField;
            }
            set {
                this.resWordListField = value;
                this.RaisePropertyChanged("resWordList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class resWebSummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class msgLeafAndEmotion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int emotionField;
        
        private int pointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int emotion {
            get {
                return this.emotionField;
            }
            set {
                this.emotionField = value;
                this.RaisePropertyChanged("emotion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
                this.RaisePropertyChanged("point");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class resEmotional : object, System.ComponentModel.INotifyPropertyChanged {
        
        private msgLeafAndEmotion[] resWordListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public msgLeafAndEmotion[] resWordList {
            get {
                return this.resWordListField;
            }
            set {
                this.resWordListField = value;
                this.RaisePropertyChanged("resWordList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class resTone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class resMeishiList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] resWordListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] resWordList {
            get {
                return this.resWordListField;
            }
            set {
                this.resWordListField = value;
                this.RaisePropertyChanged("resWordList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class resWakachiGakiResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] resWordListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] resWordList {
            get {
                return this.resWordListField;
            }
            set {
                this.resWordListField = value;
                this.RaisePropertyChanged("resWordList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class msgMecabResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idxField;
        
        private string nameField;
        
        private string posField;
        
        private string pos1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int idx {
            get {
                return this.idxField;
            }
            set {
                this.idxField = value;
                this.RaisePropertyChanged("idx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string pos {
            get {
                return this.posField;
            }
            set {
                this.posField = value;
                this.RaisePropertyChanged("pos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string pos1 {
            get {
                return this.pos1Field;
            }
            set {
                this.pos1Field = value;
                this.RaisePropertyChanged("pos1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liplis.mine.nu/XMLSchema")]
    public partial class resMecabResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private msgMecabResult[] resWordListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public msgMecabResult[] resWordList {
            get {
                return this.resWordListField;
            }
            set {
                this.resWordListField = value;
                this.RaisePropertyChanged("resWordList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClalisSoapChannel : Clalis.Api.ClalisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClalisSoapClient : System.ServiceModel.ClientBase<Clalis.Api.ClalisSoap>, Clalis.Api.ClalisSoap {
        
        public ClalisSoapClient() {
        }
        
        public ClalisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClalisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClalisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClalisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Clalis.Api.resMecabResultFull clalisMecabFull(string sentence) {
            return base.Channel.clalisMecabFull(sentence);
        }
        
        public Clalis.Api.resMecabResult clalisMecab(string sentence) {
            return base.Channel.clalisMecab(sentence);
        }
        
        public Clalis.Api.resWakachiGakiResult clalisWakachiGaki(string sentence) {
            return base.Channel.clalisWakachiGaki(sentence);
        }
        
        public Clalis.Api.resMeishiList clalisMeishiList(string sentence) {
            return base.Channel.clalisMeishiList(sentence);
        }
        
        public Clalis.Api.resTone clalisTone(string sentence, string toneFileUrl) {
            return base.Channel.clalisTone(sentence, toneFileUrl);
        }
        
        public Clalis.Api.resEmotional clalisEmotional(string sentence) {
            return base.Channel.clalisEmotional(sentence);
        }
        
        public Clalis.Api.resEmotional clalisToneEmotional(string sentence, string toneFileUrl) {
            return base.Channel.clalisToneEmotional(sentence, toneFileUrl);
        }
        
        public Clalis.Api.resWebSummary clalisWebExtractJp(string url) {
            return base.Channel.clalisWebExtractJp(url);
        }
        
        public Clalis.Api.resWebSummaryList clalisWebExtractJpSentenceList(string url) {
            return base.Channel.clalisWebExtractJpSentenceList(url);
        }
        
        public Clalis.Api.resWebSummaryList clalisWebExtractJpSentenceRelevanceList(string url) {
            return base.Channel.clalisWebExtractJpSentenceRelevanceList(url);
        }
        
        public Clalis.Api.resNewWordList clalisGetNewWordList(int number) {
            return base.Channel.clalisGetNewWordList(number);
        }
    }
}
